---
abstract: 'HTTP::Session to Sledge bindings'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Class::Trigger: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Sledge-HTTPSession
no_index:
  directory:
    - inc
    - t
requires:
  CGI: 0
  HTTP::Session: 0.28
  Moose: 0.59
  perl: 5.8.0
tests: 't/*.t t/*/*.t t/*/*/*.t t/*/*/*/*.t xt/*.t'
version: 0.04
