---
abstract: 'HTTP::Session to Sledge bindings'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Class::Trigger: 0
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
  YAML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Sledge-HTTPSession
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  CGI: 0
  Filter::Util::Call: 0
  HTML::StickyQuery: 0
  HTTP::Session: 0.28
  Moose: 0.59
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
